# Services constants
MINUTES_PER_HOUR = 60
DEFAULT_PRODUCTS_PER_PAGE = 48
DEFAULT_MAX_PAGES = 100
DEFAULT_TIMEOUT = 300
MAX_TIMEOUT = 3600
PLAYWRIGHT_TIMEOUT = 60
BEAUTIFULSOUP_TIMEOUT = 30
DEFAULT_PUBLISHER = "Неизвестно"
DEFAULT_CATEGORY = "Настольные игры"
DEFAULT_CURRENCY = "RUB"
TIMEOUT_MULTIPLIER = 3

# Admin constants
MAX_DISPLAY_ITEMS = 3

# Models constants
DEFAULT_CURRENCY = "RUB"
CURRENCY_LENGTH = 3
TITLE_MAX_LENGTH = 500
NAME_MAX_LENGTH = 200
SLUG_MAX_LENGTH = 200
PRICE_MAX_DIGITS = 10
PRICE_DECIMAL_PLACES = 2
SHOP_NAME_MAX_LENGTH = 100
PARSER_TYPE_MAX_LENGTH = 20

# Tasks constants
BOT_SEND_MESSAGE_URL = "http://bot_pricescan:8000/send_message"
BOT_SEND_ALERT_URL = "http://bot_pricescan:8000/send_alert"
DEFAULT_BATCH_LIMIT = 100
DEFAULT_DISCOVERY_LIMIT = 100
DEFAULT_MAX_KEEP = 100
DEFAULT_MAX_PAGES_PER_CALL = 12
DEFAULT_MAX_TOTAL_PAGES = 50
REFRESH_COUNTDOWN = 30
