# Generated by Django 5.2.6 on 2025-09-11 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.offer'),
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.author'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='product.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='product.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.publisher'),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.shop'),
        ),
        migrations.AddField(
            model_name='offer',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.shop'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['timestamp'], name='product_pri_timesta_da58ee_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='product_pro_title_07e491_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ean'], name='product_pro_ean_f96de8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['external_id'], name='product_pro_externa_7a3927_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['user', 'is_active'], name='product_pri_user_id_845419_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['product', 'is_active'], name='product_pri_product_a92ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='pricealert',
            index=models.Index(fields=['threshold_price'], name='product_pri_thresho_7a93ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricealert',
            unique_together={('user', 'product', 'shop', 'threshold_price', 'currency')},
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['price'], name='product_off_price_fd68e7_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['last_updated'], name='product_off_last_up_f58f32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('product', 'shop')},
        ),
    ]
