# Generated by Django 5.2.6 on 2025-09-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Предложение', 'verbose_name_plural': 'Предложения'},
        ),
        migrations.AlterModelOptions(
            name='pricealert',
            options={'verbose_name': 'Алерт', 'verbose_name_plural': 'Алерты'},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'verbose_name': 'История цен', 'verbose_name_plural': 'История цен'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'Издатель', 'verbose_name_plural': 'Издатели'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_ean_f96de8_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_pro_externa_7a3927_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ean',
        ),
        migrations.RemoveField(
            model_name='product',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='publisher',
        ),
        migrations.AddField(
            model_name='product',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.author'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.publisher'),
        ),
    ]
