# Generated by Django 5.2.6 on 2025-09-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_options_alter_offer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='authors',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
